### ISSUE TITLE
Cant select Roll if notes are more than one line

### ISSUE THREAD

**Issue by zedsupremus** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#45]
Issue:
Cant change from brains alpha complex.

Cause: any thing on the naughty side (not caused by gear or objectives) with more than one line of text. 

Suggested solution : Switch these boxes (and other big ones) to prose mirror or allow for multiple lines of text.

**Comment by OtherwiseJunk** [comment]
I can take a look at this this evening! Hopefully have a fix in place before the end of the upcoming weekend

**Comment by zedsupremus** [comment]
Additional. I may be incorrect on not caused by gear or objectives. That seems to possibly impact as well.

**Comment by OtherwiseJunk** [comment]
Closed this a little preemptively.

https://github.com/OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt/releases/tag/v0.4.1

@zedsupremus I did some minimal testing around this, but if you could confirm this release fixes your issue when you have the chance that would be great! Seemed to work on my test system but I want to confirm it before the issue gets closed out.

**Comment by zedsupremus** [comment]
Did some testing

Fixes all the boxes I listed.

However I did more testing.

I'm sorry but Mission Objectives and Gear boxes also have the same issue.

Other boxes no longer cause that issue however.

Apologies for missing them the first time

**Comment by OtherwiseJunk** [comment]
Hey no worries, sorry it took me so long to get back on this! Should have a fix in place for these last two areas this evening.

**Comment by OtherwiseJunk** [comment]
Version 0.4.2 is available, hopefully this should fix everything pray🙏

**Comment by OtherwiseJunk** [comment]
@zedsupremus sorry for such a long delay, can you confirm if this issue is still happening in the latest version (0.5.1)?

**Comment by zedsupremus** [comment]
Hey sorry i haven't had a chance to test till now
(foundry v12 however)

So, If there is content, they work perfectly so original bug solved!

HOWEVER if there is no content, you can no longer add content.
Given a new sheet has content in it, I suspect you may be aware of this.

**Comment by OtherwiseJunk** [comment]
Yeah I need to better position the edit button, but at least that portion is working.

I'll take some time this weekend to get it buttoned up for previously existing sheets though.

**Comment by OtherwiseJunk** [comment]
Ok took me way longer than I expected but this should now actually be working as of v0.6.1! Sorry for the delay I'm sure you just manually worked around it by now 😅

@zedsupremus I'll close this issue out if I don't hear from you by next week.

**Comment by zedsupremus** [comment]
unfortunately in 0.7 if a box like secret objectives is zeroed its still impossible to edit it

**Comment by OtherwiseJunk** [comment]
ha @zedsupremus v0.7.0 had some changes to the css I didn't mean to make. v0.7.1 should fix this issue and is available now.

**Comment by zedsupremus** [comment]
yeap works a treat now
