### ISSUE TITLE
Which is correct Character Sheet?

### ISSUE THREAD

**Issue by Nyogtha68** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#51]
Not sure if the sheet is displaying as intended as it looks different to the one shown on the project page.

![image](https://github.com/user-attachments/assets/98df988c-5ca0-4335-ab1b-e4ae9833464b)

**Comment by OtherwiseJunk** [comment]
That is indeed the correct character sheet. 

I still need to update the project page with this new version for less confusion, once that's done I'll close out this issue.

**Comment by Nyogtha68** [comment]
Thank you for the confirmation and thank you for the mod.

**Comment by OtherwiseJunk** [comment]
Images should reflect the state of the character sheet that's coming out in the next few days. Just want to get some basic item sheet going before I put it out.

Closing this issue for now.
