### ISSUE TITLE
Fix warnings in Foundry v12

### ISSUE THREAD

**Issue by rafal-molotkiewicz** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#55]
In the most recent Foundry version, I get the following errors:

```
The system "paranoia" is using "gridDistance" which is deprecated in favor of "grid.distance".
The system "paranoia" is using "gridUnits" which is deprecated in favor of "grid.units".
```

It seems these should be reasonably easy to fix.

**Comment by OtherwiseJunk** [comment]
Version v0.6.0 should resolve this, please let me know if you're still seeing this.

Going to leave this issue open for a week and if I don't hear anything back from others reporting issues close it out.
