### ISSUE TITLE
Jazz up the computer dice

### ISSUE THREAD

**Issue by OtherwiseJunk** [OtherwiseJunk/ParanoiaPerfectEditionSystem-foundryvtt#7]
Add some quotes for when the computer dice rolls a 6.
Add some pictures of Friend Computer. Maybe have different pictures for 1-5 than for 6.
Look into optionally playing a sound when the computer dice rolls a 6.

**Comment by Ribonizer** [comment]
Actually, from what I understand in the rules, the computer dice still gives a success on a 5. Currently the system doesn't tell us if a five is rolled so that makes it so a player can miss out on a success.

**Comment by OtherwiseJunk** [comment]
That's a good point, I'm going to add the result of the roll to the message regardless. That way tables have as much information as possible.

Hoping to get a fix going for one of the issues on here this evening, so I'll update this as part of that as well and let you know when it's available.

**Comment by OtherwiseJunk** [comment]
hey @Ribonizer version 0.4.2 should fix the issue you were mentioning

![image](https://github.com/user-attachments/assets/dd5f09dc-e1aa-4499-878c-5ac91c3e0106)

**Comment by Ribonizer** [comment]
Ayup just tested it and it's working great. Thanks!
